(function(e){function h(a){this.setMap(a)}var j=new google.maps.Geocoder;h.prototype=new google.maps.OverlayView;h.prototype.onAdd=function(){};h.prototype.onRemove=function(){};h.prototype.draw=function(){};e.goMap={};e.fn.goMap=function(a){return this.each(function(){var c=e(this).data("goMap");c||(c=e.extend(!0,{},e.goMapBase),e(this).data("goMap",c.init(this,a)));e.goMap=c})};e.goMapBase={defaults:{address:"",latitude:56.9,longitude:24.1,zoom:4,delay:200,hideByClick:!0,oneInfoWindow:!0,prefixId:"gomarker",
polyId:"gopoly",groupId:"gogroup",navigationControl:!0,navigationControlOptions:{position:"TOP_LEFT",style:"DEFAULT"},mapTypeControl:!0,mapTypeControlOptions:{position:"TOP_RIGHT",style:"DEFAULT"},scaleControl:!1,scrollwheel:!0,directions:!1,directionsResult:null,disableDoubleClickZoom:!1,streetViewControl:!1,markers:[],overlays:[],polyline:{color:"#FF0000",opacity:1,weight:2},polygon:{color:"#FF0000",opacity:1,weight:2,fillColor:"#FF0000",fillOpacity:0.2},circle:{color:"#FF0000",opacity:1,weight:2,
fillColor:"#FF0000",fillOpacity:0.2},rectangle:{color:"#FF0000",opacity:1,weight:2,fillColor:"#FF0000",fillOpacity:0.2},maptype:"HYBRID",html_prepend:"<div class=gomapMarker>",html_append:"</div>",addMarker:!1},map:null,count:0,markers:[],polylines:[],polygons:[],circles:[],rectangles:[],tmpMarkers:[],geoMarkers:[],lockGeocode:!1,bounds:null,overlays:null,overlay:null,mapId:null,plId:null,pgId:null,cId:null,rId:null,opts:null,centerLatLng:null,init:function(a,c){var b=e.extend(!0,{},e.goMapBase.defaults,
c);this.mapId=e(a);this.opts=b;b.address?this.geocode({address:b.address,center:!0}):e.isArray(b.markers)&&0<b.markers.length?b.markers[0].address?this.geocode({address:b.markers[0].address,center:!0}):this.centerLatLng=new google.maps.LatLng(b.markers[0].latitude,b.markers[0].longitude):this.centerLatLng=new google.maps.LatLng(b.latitude,b.longitude);var d={center:this.centerLatLng,disableDoubleClickZoom:b.disableDoubleClickZoom,mapTypeControl:b.mapTypeControl,streetViewControl:b.streetViewControl,
mapTypeControlOptions:{position:google.maps.ControlPosition[b.mapTypeControlOptions.position.toUpperCase()],style:google.maps.MapTypeControlStyle[b.mapTypeControlOptions.style.toUpperCase()]},mapTypeId:google.maps.MapTypeId[b.maptype.toUpperCase()],navigationControl:b.navigationControl,navigationControlOptions:{position:google.maps.ControlPosition[b.navigationControlOptions.position.toUpperCase()],style:google.maps.NavigationControlStyle[b.navigationControlOptions.style.toUpperCase()]},scaleControl:b.scaleControl,
scrollwheel:b.scrollwheel,zoom:b.zoom};this.map=new google.maps.Map(a,d);this.overlay=new h(this.map);this.overlays={polyline:{id:"plId",array:"polylines",create:"createPolyline"},polygon:{id:"pgId",array:"polygons",create:"createPolygon"},circle:{id:"cId",array:"circles",create:"createCircle"},rectangle:{id:"rId",array:"rectangles",create:"createRectangle"}};this.plId=e('<div style="display:none;"/>').appendTo(this.mapId);this.pgId=e('<div style="display:none;"/>').appendTo(this.mapId);this.cId=
e('<div style="display:none;"/>').appendTo(this.mapId);this.rId=e('<div style="display:none;"/>').appendTo(this.mapId);for(var d=0,f=b.markers.length;d<f;d++)this.createMarker(b.markers[d]);d=0;for(f=b.overlays.length;d<f;d++)this[this.overlays[b.overlays[d].type].create](b.overlays[d]);var g=this;!0==b.addMarker||"multi"==b.addMarker?google.maps.event.addListener(g.map,"click",function(a){var b=g.createMarker({position:a.latLng,draggable:!0});google.maps.event.addListener(b,"dblclick",function(){b.setMap(null);
g.removeMarker(b.id)})}):"single"==b.addMarker&&google.maps.event.addListener(g.map,"click",function(a){if(!g.singleMarker){var b=g.createMarker({position:a.latLng,draggable:!0});g.singleMarker=!0;google.maps.event.addListener(b,"dblclick",function(){b.setMap(null);g.removeMarker(b.id);g.singleMarker=!1})}});delete b.markers;delete b.overlays;return this},ready:function(a){google.maps.event.addListenerOnce(this.map,"bounds_changed",function(){return a()})},geocode:function(a,c){var b=this;setTimeout(function(){j.geocode({address:a.address},
function(d,e){e==google.maps.GeocoderStatus.OK&&a.center&&b.map.setCenter(d[0].geometry.location);e==google.maps.GeocoderStatus.OK&&c&&c.markerId?c.markerId.setPosition(d[0].geometry.location):e==google.maps.GeocoderStatus.OK&&c?b.lockGeocode&&(b.lockGeocode=!1,c.position=d[0].geometry.location,c.geocode=!0,b.createMarker(c)):e==google.maps.GeocoderStatus.OVER_QUERY_LIMIT&&b.geocode(a,c)})},this.opts.delay)},geoMarker:function(){if(0<this.geoMarkers.length&&!this.lockGeocode){this.lockGeocode=!0;
var a=this.geoMarkers.splice(0,1);this.geocode({address:a[0].address},a[0])}else if(this.lockGeocode){var c=this;setTimeout(function(){c.geoMarker()},this.opts.delay)}},setMap:function(a){delete a.mapTypeId;a.address?(this.geocode({address:a.address,center:!0}),delete a.address):a.latitude&&a.longitude&&(a.center=new google.maps.LatLng(a.latitude,a.longitude),delete a.longitude,delete a.latitude);a.mapTypeControlOptions&&a.mapTypeControlOptions.position&&(a.mapTypeControlOptions.position=google.maps.ControlPosition[a.mapTypeControlOptions.position.toUpperCase()]);
a.mapTypeControlOptions&&a.mapTypeControlOptions.style&&(a.mapTypeControlOptions.style=google.maps.MapTypeControlStyle[a.mapTypeControlOptions.style.toUpperCase()]);a.navigationControlOptions&&a.navigationControlOptions.position&&(a.navigationControlOptions.position=google.maps.ControlPosition[a.navigationControlOptions.position.toUpperCase()]);a.navigationControlOptions&&a.navigationControlOptions.style&&(a.navigationControlOptions.style=google.maps.NavigationControlStyle[a.navigationControlOptions.style.toUpperCase()]);
this.map.setOptions(a)},getMap:function(){return this.map},createListener:function(a,c,b){var d;"object"!=typeof a&&(a={type:a});"map"==a.type?d=this.map:"marker"==a.type&&a.marker?d=e(this.mapId).data(a.marker):"info"==a.type&&a.marker&&(d=e(this.mapId).data(a.marker+"info"));if(d)return google.maps.event.addListener(d,c,b);if(("marker"==a.type||"info"==a.type)&&this.getMarkerCount()!=this.getTmpMarkerCount())var f=this;setTimeout(function(){f.createListener(a,c,b)},this.opts.delay)},removeListener:function(a){google.maps.event.removeListener(a)},
setInfoWindow:function(a,c){var b=this;c.content=b.opts.html_prepend+c.content+b.opts.html_append;var d=new google.maps.InfoWindow(c);d.show=!1;e(b.mapId).data(a.id+"info",d);c.popup&&(b.openWindow(d,a,c),d.show=!0);google.maps.event.addListener(a,"click",function(){d.show&&b.opts.hideByClick?(d.close(),d.show=!1):(b.openWindow(d,a,c),d.show=!0)})},openWindow:function(a,c,b){this.opts.oneInfoWindow&&this.clearInfo();b.ajax?(a.open(this.map,c),e.ajax({url:b.ajax,success:function(b){a.setContent(b)}})):
(b.id&&a.setContent(e(b.id).html()),a.open(this.map,c))},setInfo:function(a,c){var b=e(this.mapId).data(a+"info");"object"==typeof c?b.setOptions(c):b.setContent(c)},getInfo:function(a,c){var b=e(this.mapId).data(a+"info").getContent();return c?e(b).html():b},clearInfo:function(){for(var a=0,c=this.markers.length;a<c;a++){var b=e(this.mapId).data(this.markers[a]+"info");b&&(b.close(),b.show=!1)}},fitBounds:function(a,c){var b=this;if(this.getMarkerCount()!=this.getTmpMarkerCount())setTimeout(function(){b.fitBounds(a,
c)},this.opts.delay);else{this.bounds=new google.maps.LatLngBounds;if(!a||a&&"all"==a)for(var d=0,f=this.markers.length;d<f;d++)this.bounds.extend(e(this.mapId).data(this.markers[d]).position);else if(a&&"visible"==a){d=0;for(f=this.markers.length;d<f;d++)this.getVisibleMarker(this.markers[d])&&this.bounds.extend(e(this.mapId).data(this.markers[d]).position)}else if(a&&"markers"==a&&e.isArray(c)){d=0;for(f=c.length;d<f;d++)this.bounds.extend(e(this.mapId).data(c[d]).position)}this.map.fitBounds(this.bounds)}},
getBounds:function(){return this.map.getBounds()},createPolyline:function(a){a.type="polyline";return this.createOverlay(a)},createPolygon:function(a){a.type="polygon";return this.createOverlay(a)},createCircle:function(a){a.type="circle";return this.createOverlay(a)},createRectangle:function(a){a.type="rectangle";return this.createOverlay(a)},createOverlay:function(a){var c=[];a.id||(this.count++,a.id=this.opts.polyId+this.count);switch(a.type){case "polyline":if(0<a.coords.length){for(var b=0,d=
a.coords.length;b<d;b++)c.push(new google.maps.LatLng(a.coords[b].latitude,a.coords[b].longitude));c=new google.maps.Polyline({map:this.map,path:c,strokeColor:a.color?a.color:this.opts.polyline.color,strokeOpacity:a.opacity?a.opacity:this.opts.polyline.opacity,strokeWeight:a.weight?a.weight:this.opts.polyline.weight})}else return!1;break;case "polygon":if(0<a.coords.length){b=0;for(d=a.coords.length;b<d;b++)c.push(new google.maps.LatLng(a.coords[b].latitude,a.coords[b].longitude));c=new google.maps.Polygon({map:this.map,
path:c,strokeColor:a.color?a.color:this.opts.polygon.color,strokeOpacity:a.opacity?a.opacity:this.opts.polygon.opacity,strokeWeight:a.weight?a.weight:this.opts.polygon.weight,fillColor:a.fillColor?a.fillColor:this.opts.polygon.fillColor,fillOpacity:a.fillOpacity?a.fillOpacity:this.opts.polygon.fillOpacity})}else return!1;break;case "circle":c=new google.maps.Circle({map:this.map,center:new google.maps.LatLng(a.latitude,a.longitude),radius:a.radius,strokeColor:a.color?a.color:this.opts.circle.color,
strokeOpacity:a.opacity?a.opacity:this.opts.circle.opacity,strokeWeight:a.weight?a.weight:this.opts.circle.weight,fillColor:a.fillColor?a.fillColor:this.opts.circle.fillColor,fillOpacity:a.fillOpacity?a.fillOpacity:this.opts.circle.fillOpacity});break;case "rectangle":c=new google.maps.Rectangle({map:this.map,bounds:new google.maps.LatLngBounds(new google.maps.LatLng(a.sw.latitude,a.sw.longitude),new google.maps.LatLng(a.ne.latitude,a.ne.longitude)),strokeColor:a.color?a.color:this.opts.circle.color,
strokeOpacity:a.opacity?a.opacity:this.opts.circle.opacity,strokeWeight:a.weight?a.weight:this.opts.circle.weight,fillColor:a.fillColor?a.fillColor:this.opts.circle.fillColor,fillOpacity:a.fillOpacity?a.fillOpacity:this.opts.circle.fillOpacity});break;default:return!1}this.addOverlay(a,c);return c},addOverlay:function(a,c){e(this[this.overlays[a.type].id]).data(a.id,c);this[this.overlays[a.type].array].push(a.id)},setOverlay:function(a,c,b){c=e(this[this.overlays[a].id]).data(c);if(b.coords&&0<b.coords.length){a=
[];for(var d=0,f=b.coords.length;d<f;d++)a.push(new google.maps.LatLng(b.coords[d].latitude,b.coords[d].longitude));b.path=a;delete b.coords}else b.ne&&b.sw?(b.bounds=new google.maps.LatLngBounds(new google.maps.LatLng(b.sw.latitude,b.sw.longitude),new google.maps.LatLng(b.ne.latitude,b.ne.longitude)),delete b.ne,delete b.sw):b.latitude&&b.longitude&&(b.center=new google.maps.LatLng(b.latitude,b.longitude),delete b.latitude,delete b.longitude);c.setOptions(b)},showHideOverlay:function(a,c,b){"undefined"===
typeof b&&(b=this.getVisibleOverlay(a,c)?!1:!0);b?e(this[this.overlays[a].id]).data(c).setMap(this.map):e(this[this.overlays[a].id]).data(c).setMap(null)},getVisibleOverlay:function(a,c){return e(this[this.overlays[a].id]).data(c).getMap()?!0:!1},getOverlaysCount:function(a){return this[this.overlays[a].array].length},removeOverlay:function(a,c){var b=e.inArray(c,this[this.overlays[a].array]);return-1<b?(b=this[this.overlays[a].array].splice(b,1),b=b[0],e(this[this.overlays[a].id]).data(b).setMap(null),
e(this[this.overlays[a].id]).removeData(b),!0):!1},clearOverlays:function(a){for(var c=0,b=this[this.overlays[a].array].length;c<b;c++){var d=this[this.overlays[a].array][c];e(this[this.overlays[a].id]).data(d).setMap(null);e(this[this.overlays[a].id]).removeData(d)}this[this.overlays[a].array]=[]},showHideMarker:function(a,c){if("undefined"===typeof c)if(this.getVisibleMarker(a)){e(this.mapId).data(a).setVisible(!1);var b=e(this.mapId).data(a+"info");b&&b.show&&(b.close(),b.show=!1)}else e(this.mapId).data(a).setVisible(!0);
else e(this.mapId).data(a).setVisible(c)},showHideMarkerByGroup:function(a,c){for(var b=0,d=this.markers.length;b<d;b++){var f=this.markers[b],g=e(this.mapId).data(f);if(g.group==a)if("undefined"===typeof c)if(this.getVisibleMarker(f)){if(g.setVisible(!1),(f=e(this.mapId).data(f+"info"))&&f.show)f.close(),f.show=!1}else g.setVisible(!0);else g.setVisible(c)}},getVisibleMarker:function(a){return e(this.mapId).data(a).getVisible()},getMarkerCount:function(){return this.markers.length},getTmpMarkerCount:function(){return this.tmpMarkers.length},
getVisibleMarkerCount:function(){return this.getMarkers("visiblesInMap").length},getMarkerByGroupCount:function(a){return this.getMarkers("group",a).length},getMarkers:function(a,c){var b=[];switch(a){case "json":for(var d=0,f=this.markers.length;d<f;d++){var g="'"+d+"': '"+e(this.mapId).data(this.markers[d]).getPosition().toUrlValue()+"'";b.push(g)}b="{'markers':{"+b.join(",")+"}}";break;case "data":d=0;for(f=this.markers.length;d<f;d++)g="marker["+d+"]="+e(this.mapId).data(this.markers[d]).getPosition().toUrlValue(),
b.push(g);b=b.join("&");break;case "visiblesInBounds":d=0;for(f=this.markers.length;d<f;d++)this.isVisible(e(this.mapId).data(this.markers[d]).getPosition())&&b.push(this.markers[d]);break;case "visiblesInMap":d=0;for(f=this.markers.length;d<f;d++)this.getVisibleMarker(this.markers[d])&&b.push(this.markers[d]);break;case "group":if(c){d=0;for(f=this.markers.length;d<f;d++)e(this.mapId).data(this.markers[d]).group==c&&b.push(this.markers[d])}break;case "markers":d=0;for(f=this.markers.length;d<f;d++)g=
e(this.mapId).data(this.markers[d]),b.push(g);break;default:d=0;for(f=this.markers.length;d<f;d++)g=e(this.mapId).data(this.markers[d]).getPosition().toUrlValue(),b.push(g)}return b},getVisibleMarkers:function(){return this.getMarkers("visiblesInBounds")},createMarker:function(a){a.geocode||(this.count++,a.id||(a.id=this.opts.prefixId+this.count),this.tmpMarkers.push(a.id));if(a.address&&!a.geocode)this.geoMarkers.push(a),this.geoMarker();else if(a.latitude&&a.longitude||a.position){var c={map:this.map};
c.id=a.id;c.group=a.group?a.group:this.opts.groupId;c.zIndex=a.zIndex?a.zIndex:0;c.zIndexOrg=a.zIndexOrg?a.zIndexOrg:0;!1==a.visible&&(c.visible=a.visible);a.title&&(c.title=a.title);a.draggable&&(c.draggable=a.draggable);a.icon&&a.icon.image?(c.icon=a.icon.image,a.icon.shadow&&(c.shadow=a.icon.shadow)):a.icon?c.icon=a.icon:this.opts.icon&&this.opts.icon.image?(c.icon=this.opts.icon.image,this.opts.icon.shadow&&(c.shadow=this.opts.icon.shadow)):this.opts.icon&&(c.icon=this.opts.icon);c.position=a.position?
a.position:new google.maps.LatLng(a.latitude,a.longitude);c=new google.maps.Marker(c);a.html&&(!a.html.content&&!a.html.ajax&&!a.html.id?a.html={content:a.html}:a.html.content||(a.html.content=null),this.setInfoWindow(c,a.html));this.addMarker(c);return c}},addMarker:function(a){e(this.mapId).data(a.id,a);this.markers.push(a.id)},setMarker:function(a,c){var b=e(this.mapId).data(a);delete c.id;delete c.visible;if(c.icon){var d=c.icon;delete c.icon;d&&"default"==d?this.opts.icon&&this.opts.icon.image?
(c.icon=this.opts.icon.image,this.opts.icon.shadow&&(c.shadow=this.opts.icon.shadow)):this.opts.icon&&(c.icon=this.opts.icon):d&&d.image?(c.icon=d.image,d.shadow&&(c.shadow=d.shadow)):d&&(c.icon=d)}if(c.address)this.geocode({address:c.address},{markerId:b}),delete c.address,delete c.latitude,delete c.longitude,delete c.position;else if((c.latitude&&c.longitude||c.position)&&!c.position)c.position=new google.maps.LatLng(c.latitude,c.longitude);b.setOptions(c)},removeMarker:function(a){a=e.inArray(a,
this.markers);if(-1<a){this.tmpMarkers.splice(a,1);a=this.markers.splice(a,1);var c=a[0];a=e(this.mapId).data(c);var b=e(this.mapId).data(c+"info");a.setVisible(!1);a.setMap(null);e(this.mapId).removeData(c);b&&(b.close(),b.show=!1,e(this.mapId).removeData(c+"info"));return!0}return!1},clearMarkers:function(){for(var a=0,c=this.markers.length;a<c;a++){var b=this.markers[a],d=e(this.mapId).data(b),f=e(this.mapId).data(b+"info");d.setVisible(!1);d.setMap(null);e(this.mapId).removeData(b);f&&(f.close(),
f.show=!1,e(this.mapId).removeData(b+"info"))}this.lockGeocode=this.singleMarker=!1;this.markers=[];this.tmpMarkers=[];this.geoMarkers=[]},isVisible:function(a){return this.map.getBounds().contains(a)}}})(jQuery);
