<?php
get_template_part('widgets/tabs_widget');
get_template_part('widgets/tweets-widget');
get_template_part('widgets/flickr-widget');
get_template_part('widgets/facebook-like-widget');
get_template_part('widgets/125_125');
get_template_part('widgets/social_links');
get_template_part('widgets/contact_info');
get_template_part('widgets/recent-works-widget');